# Generated by Django 5.2 on 2025-05-04 06:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="uuid",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(unique=True, verbose_name="Промокод"),
                ),
                ("description", models.CharField(verbose_name="Описание")),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "rental_cost_discount",
                    models.IntegerField(
                        default=0,
                        help_text="Скидка только на аренду в процентах",
                        verbose_name="% Скидки",
                    ),
                ),
            ],
            options={
                "verbose_name": "промокод",
                "verbose_name_plural": "Промокоды",
                "ordering": ["-updated_time"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UsedCoupon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="uuid",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_coupons",
                        to="promo.coupon",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_coupons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_time"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "coupon"), name="unique_used_coupon"
                    )
                ],
            },
        ),
    ]
