# Generated by Django 5.2 on 2025-05-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="car_type",
            field=models.CharField(
                choices=[
                    ("hatchback", "Хэтчбек"),
                    ("sedan", "Седан"),
                    ("suv", "Внедорожник"),
                    ("muv", "Минивэн"),
                    ("coupe", "Купе"),
                    ("convertible", "Кабриолет"),
                    ("pickup", "Пикап"),
                ],
                default="sedan",
                max_length=32,
                verbose_name="Тип кузова (sedan, suv и т.д.)",
            ),
            preserve_default=False,
        ),
    ]
