# Generated by Django 5.2 on 2025-05-06 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_alter_carfleet_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cars",
            name="available_from",
        ),
        migrations.RemoveField(
            model_name="cars",
            name="available_to",
        ),
    ]
