# Generated by Django 5.2 on 2025-05-23 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0005_remove_cars_available_from_remove_cars_available_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cars",
            name="supports_delivery",
        ),
    ]
