# Generated by Django 5.2.1 on 2025-06-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0007_alter_carfleet_owner_phone_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="carimage",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="carimage",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="cars",
            name="car_type",
            field=models.CharField(
                choices=[
                    ("hatchback", "Хэтчбек"),
                    ("sedan", "Седан"),
                    ("suv", "Внедорожник"),
                    ("mid_suv", "Mid-size SUV"),
                    ("crossover", "Кроссовер"),
                    ("muv", "Минивэн"),
                    ("coupe", "Купе"),
                    ("convertible", "Кабриолет"),
                    ("pickup", "Пикап"),
                ],
                max_length=32,
                verbose_name="Тип кузова (sedan, suv и т.д.)",
            ),
        ),
    ]
