# Generated by Django 5.2.1 on 2025-06-18 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0008_alter_carimage_options_carimage_order_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="carimage",
            options={"ordering": ["-updated_time"]},
        ),
        migrations.RemoveField(
            model_name="carimage",
            name="order",
        ),
    ]
