# Generated by Django 5.2.1 on 2025-06-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0009_alter_carimage_options_remove_carimage_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="carimage",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="carimage",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
