# Generated by Django 5.2 on 2025-05-13 17:48

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="date_of_birth",
        ),
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[common.validators.minimum_age_validator],
                verbose_name="Возраст",
            ),
        ),
    ]
