# Generated by Django 5.2 on 2025-05-26 07:48

import api.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_date_of_birth_user_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="profile_images/",
                validators=[
                    api.users.validators.profile_photo_extension_validator
                ],
                verbose_name="Фото профиля",
            ),
        ),
    ]
