# Generated by Django 5.2 on 2025-05-26 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_image_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="image_file",
            new_name="profile_image",
        ),
    ]
