# Generated by Django 5.2 on 2025-05-26 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_rename_image_file_user_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Неверный номер",
                        regex="^\\+998(9[0-1]|9[3-5]|9[7-9]|33|55|77|88)[0-9]{7}$",
                    )
                ],
                verbose_name="Номер телефона",
            ),
        ),
    ]
