# Generated by Django 5.2.1 on 2025-06-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[
                    ("ru", "Русский"),
                    ("uz", "Oʻzbekcha"),
                    ("en", "English"),
                ],
                default="uz",
                max_length=2,
                verbose_name="Язык интерфейса",
            ),
        ),
    ]
