# Generated by Django 5.2.1 on 2025-06-24 15:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="uuid",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[("android", "Android"), ("ios", "iOS")],
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("version", models.CharField(max_length=20)),
                ("link", models.URLField()),
            ],
            options={
                "ordering": ["-updated_time"],
                "abstract": False,
            },
        ),
    ]
