# Generated by Django 5.2 on 2025-04-30 15:58

import common.documents.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DriverLicense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="uuid",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("pending", "В процессе"),
                            ("approved", "Подтверждено"),
                            ("rejected", "Отклонено"),
                        ],
                        default="pending",
                        verbose_name="Состояние валидации",
                    ),
                ),
                (
                    "user_approved",
                    models.BooleanField(
                        default=False, verbose_name="Подтверждено пользователем"
                    ),
                ),
                (
                    "surname",
                    models.CharField(
                        blank=True, null=True, verbose_name="Фамилия (1)"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, null=True, verbose_name="Имя (2)"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения (3)"
                    ),
                ),
                (
                    "acquire_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Дата получения (4a)",
                    ),
                ),
                (
                    "validity_period",
                    models.CharField(
                        blank=True, null=True, verbose_name="Срок действия (4b)"
                    ),
                ),
                (
                    "has_b_category",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Имеет ли B категорию (9)",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        unique=True, verbose_name="Серийный номер (10)"
                    ),
                ),
                (
                    "image_file",
                    models.FileField(
                        upload_to="driverlicense_images/",
                        validators=[
                            common.documents.validators.document_file_extension_validator
                        ],
                        verbose_name="Фото прав",
                    ),
                ),
                (
                    "image_file_back",
                    models.FileField(
                        upload_to="driverlicense_images/",
                        validators=[
                            common.documents.validators.document_file_extension_validator
                        ],
                        verbose_name="Фото прав сзади",
                    ),
                ),
            ],
            options={
                "verbose_name": "Водительские права",
                "verbose_name_plural": "Водительские права",
                "ordering": ["-updated_time"],
                "abstract": False,
            },
        ),
    ]
