# Generated by Django 5.2 on 2025-05-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driverlicenses", "0004_alter_driverlicense_serial_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driverlicense",
            name="validation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидание авто проверки"),
                    ("extract_failed", "Авто проверка не выполнена"),
                    ("extract_verified", "Авто проверка успешна"),
                    ("approved", "Подтверждено"),
                    ("rejected", "Отклонено"),
                ],
                default="pending",
                verbose_name="Состояние валидации",
            ),
        ),
    ]
