# Generated by Django 5.2 on 2025-05-13 09:48

import common.documents.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driverlicenses", "0005_alter_driverlicense_validation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driverlicense",
            name="image_file",
            field=models.FileField(
                blank=True,
                upload_to="driverlicense_images/",
                validators=[
                    common.documents.validators.document_file_extension_validator
                ],
                verbose_name="Фото прав",
            ),
        ),
        migrations.AlterField(
            model_name="driverlicense",
            name="image_file_back",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="driverlicense_images/",
                validators=[
                    common.documents.validators.document_file_extension_validator
                ],
                verbose_name="Фото прав сзади",
            ),
        ),
    ]
