# Generated by Django 5.2 on 2025-06-03 17:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="uuid",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "own_referral_code",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Свой реферальный токен",
                    ),
                ),
                (
                    "used_referral_code",
                    models.UUIDField(
                        blank=True,
                        null=True,
                        verbose_name="Использованый реферальный токен",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Текущий баланс реферальной скидки",
                    ),
                ),
                (
                    "users_invited",
                    models.IntegerField(
                        default=0,
                        verbose_name="Число приглашенных пользователей",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "реферальная информация",
                "verbose_name_plural": "Реферальная информация",
                "ordering": ["-updated_time"],
                "abstract": False,
            },
        ),
    ]
