# Generated by Django 5.2 on 2025-05-04 16:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cars", "0002_initial"),
        ("promo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="uuid",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("agreed_to_terms", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Заказ получен, ожидает подтверждения"),
                            ("on_process", "Подготовка к передаче"),
                            ("on_delivery", "В пути, если выбрана доставка"),
                            ("accepted", "Автомобиль у пользователя"),
                            ("finished", "Аренда завершена"),
                            (
                                "cancelled",
                                "Отменено пользователем или администратором",
                            ),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                (
                    "delivery_option",
                    models.CharField(
                        choices=[
                            ("pickup", "Самовывоз"),
                            ("delivery", "Доставка"),
                        ],
                        max_length=20,
                        verbose_name="Способ получения",
                    ),
                ),
                ("delivery_latitude", models.FloatField(blank=True, null=True)),
                (
                    "delivery_longitude",
                    models.FloatField(blank=True, null=True),
                ),
                ("delivery_price", models.PositiveIntegerField(default=50000)),
                (
                    "courier_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "courier_phone",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "driver_requested",
                    models.BooleanField(
                        default=False, verbose_name="Водитель запрошен"
                    ),
                ),
                (
                    "fuel_level",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Уровень топлива при передаче (%)",
                    ),
                ),
                (
                    "identity_verified",
                    models.BooleanField(
                        default=False, verbose_name="Верификация личности"
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Заметки администратора",
                    ),
                ),
                (
                    "total_price_before_discount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cars.cars",
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="promo.coupon",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["-created_time"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BookingStatusLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="uuid",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "old_status",
                    models.CharField(
                        choices=[
                            ("pending", "В ожидании"),
                            ("on_process", "В процессе"),
                            ("on_delivery", "На доставке"),
                            ("accepted", "Принято"),
                            ("finished", "Завершено"),
                            ("cancelled", "Отменено"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("pending", "В ожидании"),
                            ("on_process", "В процессе"),
                            ("on_delivery", "На доставке"),
                            ("accepted", "Принято"),
                            ("finished", "Завершено"),
                            ("cancelled", "Отменено"),
                        ],
                        max_length=20,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="bookings.booking",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "статус бронирования",
                "verbose_name_plural": "Статусы бронирований",
            },
        ),
    ]
