# Generated by Django 5.2 on 2025-05-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_deposit"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="deposit",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12
            ),
        ),
    ]
