# Generated by Django 5.2 on 2025-05-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_booking_return_pickup_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("CARD", "Карта"), ("CASH", "Наличные")],
                help_text="Выбранный клиентом метод оплаты: карта или наличные",
                max_length=10,
                null=True,
                verbose_name="Метод оплаты",
            ),
        ),
    ]
