# Generated by Django 5.2 on 2025-05-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_booking_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="return_pickup_price",
            field=models.PositiveIntegerField(
                default=50000,
                verbose_name="Стоимость забора авто с адреса клиента",
            ),
        ),
    ]
