# Generated by Django 5.2 on 2025-06-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_booking_return_pickup_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="total_price_before_discount",
        ),
        migrations.AddField(
            model_name="booking",
            name="daily_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="days",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="driver_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="rental_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="total_after_referral",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="total_before_discount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="booking",
            name="delivery_price",
            field=models.DecimalField(
                decimal_places=2, default=50000, max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="return_pickup_price",
            field=models.DecimalField(
                decimal_places=2,
                default=50000,
                max_digits=12,
                verbose_name="Стоимость забора авто с адреса клиента",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="total_price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
