# Generated by Django 5.2 on 2025-06-03 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_booking_return_pickup_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="agreed_to_terms",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="fuel_level",
        ),
    ]
