# Generated by Django 5.2 on 2025-06-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bookings",
            "0007_remove_booking_total_price_before_discount_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="referral_discount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12
            ),
        ),
    ]
