# Generated by Django 5.2 on 2025-06-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0008_booking_referral_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="promocode_discount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12
            ),
        ),
    ]
