# Generated by Django 5.2 on 2025-06-05 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_remove_booking_agreed_to_terms_and_more"),
        ("bookings", "0009_booking_promocode_discount"),
    ]

    operations = []
