# Generated by Django 5.2 on 2025-06-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0010_merge_20250605_2031"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="agreed_to_terms",
            field=models.BooleanField(default=False),
        ),
    ]
