# Generated by Django 5.2 on 2025-04-30 15:58

import api.passports.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PassportInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="uuid",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("pending", "В процессе"),
                            ("approwed", "Подтверждено"),
                            ("rejected", "Отклонено"),
                        ],
                        default="pending",
                        verbose_name="Состояние валидации",
                    ),
                ),
                ("name", models.CharField(verbose_name="Имя")),
                ("surname", models.CharField(verbose_name="Фамилия")),
                (
                    "pinfl",
                    models.CharField(
                        unique=True,
                        validators=[api.passports.validators.PinflValidator],
                        verbose_name="ПИНФЛ",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(verbose_name="Дата рождения"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="passport_images/",
                        verbose_name="Фото пассорта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Паспорт",
                "verbose_name_plural": "Паспорта",
                "ordering": ["-updated_time"],
                "abstract": False,
            },
        ),
    ]
