# Generated by Django 5.2 on 2025-05-05 15:40

import api.passports.validators
import common.documents.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passports", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Passport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="uuid",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "is_id_card",
                    models.BooleanField(
                        default=True, verbose_name="Является ли ID картой"
                    ),
                ),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидание авто проверки"),
                            ("extract_failed", "Авто проверка не выполнена"),
                            ("extract_verified", "Авто проверка успешна"),
                            ("approved", "Подтверждено"),
                            ("rejected", "Отклонено"),
                        ],
                        default="pending",
                        verbose_name="Состояние валидации",
                    ),
                ),
                ("name", models.CharField(verbose_name="Имя")),
                ("surname", models.CharField(verbose_name="Фамилия")),
                (
                    "pinfl",
                    models.CharField(
                        unique=True,
                        validators=[api.passports.validators.PinflValidator],
                        verbose_name="ПИНФЛ",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(verbose_name="Дата рождения"),
                ),
                (
                    "image_file",
                    models.FileField(
                        upload_to="driverlicense_images/",
                        validators=[
                            common.documents.validators.document_file_extension_validator
                        ],
                        verbose_name="Фото паспорта",
                    ),
                ),
                (
                    "image_file_back",
                    models.FileField(
                        null=True,
                        upload_to="driverlicense_images/",
                        validators=[
                            common.documents.validators.document_file_extension_validator
                        ],
                        verbose_name="Фото паспорта сзади (если ID карта)",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passport",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь. Владелец паспорта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Паспорт",
                "verbose_name_plural": "Паспорта",
                "ordering": ["-updated_time"],
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="PassportInfo",
        ),
    ]
