# Generated by Django 5.2 on 2025-05-05 15:57

import api.passports.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passports", "0003_passport_delete_passportinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passport",
            name="date_of_birth",
            field=models.DateField(null=True, verbose_name="Дата рождения"),
        ),
        migrations.AlterField(
            model_name="passport",
            name="name",
            field=models.CharField(null=True, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="passport",
            name="pinfl",
            field=models.CharField(
                blank=True,
                null=True,
                unique=True,
                validators=[api.passports.validators.PinflValidator],
                verbose_name="ПИНФЛ",
            ),
        ),
        migrations.AlterField(
            model_name="passport",
            name="surname",
            field=models.CharField(null=True, verbose_name="Фамилия"),
        ),
    ]
