# Generated by Django 5.2 on 2025-05-07 17:21

import common.documents.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "passports",
            "0004_alter_passport_date_of_birth_alter_passport_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="passport",
            name="image_file",
            field=models.FileField(
                upload_to="passport_images/",
                validators=[
                    common.documents.validators.document_file_extension_validator
                ],
                verbose_name="Фото паспорта",
            ),
        ),
        migrations.AlterField(
            model_name="passport",
            name="image_file_back",
            field=models.FileField(
                null=True,
                upload_to="passport_images/",
                validators=[
                    common.documents.validators.document_file_extension_validator
                ],
                verbose_name="Фото паспорта сзади (если ID карта)",
            ),
        ),
    ]
