# Generated by Django 5.2 on 2025-05-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "passports",
            "0004_alter_passport_date_of_birth_alter_passport_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="passport",
            name="middlename",
            field=models.CharField(
                blank=True, null=True, verbose_name="Отчество"
            ),
        ),
    ]
