# Generated by Django 5.2 on 2025-05-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passports", "0005_passport_middlename"),
    ]

    operations = [
        migrations.AddField(
            model_name="passport",
            name="serial_and_number",
            field=models.CharField(
                blank=True, null=True, verbose_name="Серия и номер паспорта"
            ),
        ),
    ]
