# Generated by Django 5.2 on 2025-05-07 16:20

import api.passports.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passports", "0006_passport_serial_and_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passport",
            name="pinfl",
            field=models.BigIntegerField(
                blank=True,
                null=True,
                unique=True,
                validators=[api.passports.validators.PinflValidator],
                verbose_name="ПИНФЛ",
            ),
        ),
    ]
