# Generated by Django 5.2 on 2025-05-08 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("passports", "0005_alter_passport_image_file_and_more"),
        ("passports", "0007_alter_passport_pinfl"),
    ]

    operations = []
