# Generated by Django 5.2 on 2025-05-13 09:48

import common.documents.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passports", "0008_merge_20250508_1603"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passport",
            name="date_of_birth",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата рождения"
            ),
        ),
        migrations.AlterField(
            model_name="passport",
            name="image_file",
            field=models.FileField(
                blank=True,
                upload_to="passport_images/",
                validators=[
                    common.documents.validators.document_file_extension_validator
                ],
                verbose_name="Фото паспорта",
            ),
        ),
        migrations.AlterField(
            model_name="passport",
            name="image_file_back",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="passport_images/",
                validators=[
                    common.documents.validators.document_file_extension_validator
                ],
                verbose_name="Фото паспорта сзади (если ID карта)",
            ),
        ),
        migrations.AlterField(
            model_name="passport",
            name="name",
            field=models.CharField(blank=True, null=True, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="passport",
            name="surname",
            field=models.CharField(
                blank=True, null=True, verbose_name="Фамилия"
            ),
        ),
    ]
