# Generated by Django 5.2 on 2025-05-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validate_uz", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="validateuz",
            options={
                "verbose_name": "данные из validate.uz",
                "verbose_name_plural": "Данные из validate.uz",
            },
        ),
        migrations.AddField(
            model_name="validateuz",
            name="address_city_id",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="ID города адреса проживания",
            ),
        ),
        migrations.AddField(
            model_name="validateuz",
            name="address_place",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Адрес проживания (улица, дом)",
            ),
        ),
        migrations.AddField(
            model_name="validateuz",
            name="address_region_id",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="ID региона адреса проживания",
            ),
        ),
    ]
