# Generated by Django 5.2 on 2025-05-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "validate_uz",
            "0002_alter_validateuz_options_validateuz_address_city_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="validateuz",
            name="debts_sum",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Сумма долгов"
            ),
        ),
    ]
