# Generated by Django 5.2 on 2025-05-05 11:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="uuid",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "method",
                    models.CharField(
                        choices=[("CARD", "Карта"), ("CASH", "Наличные")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "Инициализирован"),
                            ("PENDING", "Ожидает"),
                            ("SUCCESS", "Успешно"),
                            ("FAILED", "Ошибка"),
                            ("CANCELLED", "Отменён"),
                        ],
                        default="INITIATED",
                        max_length=10,
                    ),
                ),
                (
                    "sale_transaction_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "sale_success_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("sale_amount", models.BigIntegerField(blank=True, null=True)),
                (
                    "hold_transaction_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "hold_success_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "deposit_amount",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "hold_status",
                    models.CharField(
                        choices=[
                            ("NONE", "Без холда"),
                            ("AUTHORIZED", "Авторизован"),
                            ("CAPTURED", "Списан"),
                            ("RELEASED", "Отменён"),
                        ],
                        default="NONE",
                        max_length=10,
                    ),
                ),
                (
                    "hold_release_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "atm_invoice",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "request_sign",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("keep_deposit", models.BooleanField(default=False)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_time"],
                "abstract": False,
            },
        ),
    ]
