# Generated by Django 5.2 on 2025-05-14 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment_card_balance_payment_card_holder_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_id", models.BigIntegerField()),
                ("card_token", models.CharField(max_length=255)),
                ("pan", models.CharField(max_length=20)),
                ("expiry", models.CharField(max_length=4)),
                ("card_holder", models.CharField(blank=True, max_length=100)),
                ("card_phone", models.CharField(blank=True, max_length=20)),
                ("balance", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "card_id")},
            },
        ),
    ]
