# Generated by Django 5.2 on 2025-05-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_card"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[("card", "Card"), ("cash", "Cash")],
                default="card",
                max_length=10,
            ),
        ),
    ]
