# Generated by Django 5.2 on 2025-05-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="reverse_response",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="reverse_transaction_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
